# Generated by Django 4.2 on 2023-12-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CityTitle", models.CharField(max_length=100, verbose_name="نام شهر")),
                (
                    "IsCapital",
                    models.BooleanField(default=False, verbose_name="مرکز استان است؟"),
                ),
                (
                    "CityCode",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="کد شهر"
                    ),
                ),
            ],
            options={
                "verbose_name": "شهر",
                "verbose_name_plural": "شهرها",
            },
        ),
        migrations.CreateModel(
            name="CityDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DistrictTitle",
                    models.CharField(max_length=50, verbose_name="نام منطقه"),
                ),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.city",
                        verbose_name="شهر مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "ناحیه شهری",
                "verbose_name_plural": "نواحی شهری",
            },
        ),
        migrations.CreateModel(
            name="ConstValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Caption", models.CharField(max_length=50, verbose_name="عنوان")),
                ("Code", models.CharField(max_length=100, verbose_name="کد")),
                (
                    "IsActive",
                    models.BooleanField(default=True, verbose_name="فعال است؟"),
                ),
                (
                    "OrderNumber",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="شماره ترتیب"
                    ),
                ),
                (
                    "ConstValue",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="مقدار مربوطه"
                    ),
                ),
                (
                    "Parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.constvalue",
                        verbose_name="شناسه پدر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ثابت",
                "verbose_name_plural": "مقادیر ثابت",
                "ordering": ["Parent_id", "OrderNumber"],
            },
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150, verbose_name="رشته")),
            ],
            options={
                "verbose_name": "رشته تحصیلی",
                "verbose_name_plural": "رشته های تحصیلی",
                "ordering": ("Title",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationChartRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "سمت و سطح",
                "verbose_name_plural": "سمت ها و سطح ها",
            },
        ),
        migrations.CreateModel(
            name="PageInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PageName", models.CharField(max_length=30, verbose_name="نام صفحه")),
                (
                    "EnglishName",
                    models.CharField(max_length=30, verbose_name="نام لاتین صفحه"),
                ),
                (
                    "ColorSet",
                    models.CharField(max_length=30, verbose_name="رنگ آیکون صفحه"),
                ),
                (
                    "IconName",
                    models.CharField(max_length=30, verbose_name="آیکون صفحه"),
                ),
                (
                    "ShowDetail",
                    models.BooleanField(
                        default=False, verbose_name="جزییات نمایش داده شود؟"
                    ),
                ),
                (
                    "OrderNumber",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="ترتیب نمایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات صفحه",
                "verbose_name_plural": "اطلاعات صفحات",
            },
        ),
        migrations.CreateModel(
            name="PostalAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "AddressText",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "No",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="پلاک"
                    ),
                ),
                (
                    "UnitNo",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="شماره واحد"
                    ),
                ),
                (
                    "PostalCode",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="کد پستی"
                    ),
                ),
                (
                    "IsDefault",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش فرض است؟"
                    ),
                ),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.city",
                        verbose_name="شهر محل زندگی",
                    ),
                ),
                (
                    "CityDistrict",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HR.citydistrict",
                        verbose_name="منطقه",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس پستی",
                "verbose_name_plural": "آدرس های پستی",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ProvinceTitle",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="نام استان"
                    ),
                ),
                (
                    "AbbreviationCode",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="کد استان"
                    ),
                ),
                (
                    "PhoneCode",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="پیش شماره استان"
                    ),
                ),
            ],
            options={
                "verbose_name": "استان",
                "verbose_name_plural": "استان ها",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "RoleId",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="کد سمت"
                    ),
                ),
                ("RoleName", models.CharField(max_length=100, verbose_name="نام سمت")),
                (
                    "HasLevel",
                    models.BooleanField(default=False, verbose_name="دارای سطح"),
                ),
                (
                    "HasSuperior",
                    models.BooleanField(default=False, verbose_name="ارشد دارد"),
                ),
            ],
            options={
                "verbose_name": "سمت",
                "verbose_name_plural": "سمت ها",
                "db_table": "Role",
            },
        ),
        migrations.CreateModel(
            name="RoleGroupTargetException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RoleGroup",
                    models.CharField(max_length=100, verbose_name="گروه مبدا"),
                ),
                (
                    "RoleGroupTarget",
                    models.CharField(max_length=100, verbose_name="گروه مقصد"),
                ),
            ],
            options={
                "verbose_name": "گروه سمت",
                "verbose_name_plural": "گروه های سمت ها",
            },
        ),
        migrations.CreateModel(
            name="RoleLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LevelName", models.CharField(max_length=20, verbose_name="نام سطح")),
            ],
            options={
                "verbose_name": "سطح",
                "verbose_name_plural": "سطوح",
                "db_table": "RoleLevel",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "TeamCode",
                    models.CharField(
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name="کدتیم",
                    ),
                ),
                ("TeamName", models.CharField(max_length=100, verbose_name="نام تیم")),
                (
                    "ActiveInService",
                    models.BooleanField(default=True, null=True, verbose_name=" کتاب"),
                ),
                (
                    "ActiveInEvaluation",
                    models.BooleanField(
                        default=True, null=True, verbose_name="ارزیابی"
                    ),
                ),
                (
                    "IsActive",
                    models.BooleanField(default=True, verbose_name="آیا تیم فعال است؟"),
                ),
            ],
            options={
                "verbose_name": "تیم",
                "verbose_name_plural": "تیم ها",
                "db_table": "Team",
            },
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=300)),
                ("AppName", models.CharField(default=None, max_length=100, null=True)),
                ("AuthLoginKey", models.CharField(max_length=300, null=True)),
                ("RequestDate", models.DateTimeField(default=None)),
                ("EnterDate", models.DateTimeField(default=None, null=True)),
                ("RequestUrl", models.CharField(max_length=300, null=True)),
                ("EnterUrl", models.CharField(max_length=300, null=True)),
                ("IP", models.GenericIPAddressField(null=True)),
                ("UserAgent", models.CharField(max_length=300, null=True)),
                ("ChangedUserInfo", models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "UserName",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="نام کاربری",
                    ),
                ),
                ("FirstName", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "LastName",
                    models.CharField(max_length=200, verbose_name="نام خانوادگی"),
                ),
                (
                    "FirstNameEnglish",
                    models.CharField(
                        blank=True, max_length=80, null=True, verbose_name="نام لاتین"
                    ),
                ),
                (
                    "LastNameEnglish",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام خانوادگی لاتین",
                    ),
                ),
                (
                    "FatherName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام پدر"
                    ),
                ),
                (
                    "ContractDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ شروع همکاری"
                    ),
                ),
                (
                    "ContractEndDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان همکاری"
                    ),
                ),
                (
                    "About",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="درباره من"
                    ),
                ),
                ("Gender", models.BooleanField(default=False, verbose_name="جنسیت")),
                (
                    "CVFile",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="فایل رزومه"
                    ),
                ),
                (
                    "NumberOfChildren",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="تعداد فرزند"
                    ),
                ),
                (
                    "NationalCode",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "BirthDate",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "IdentityNumber",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="شماره شناسنامه",
                    ),
                ),
                (
                    "IdentityRegisterDate",
                    models.DateField(null=True, verbose_name="تاریخ صدور شناسنامه"),
                ),
                (
                    "IdentitySerialNumber",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="سریال شناسنامه",
                    ),
                ),
                (
                    "InsuranceNumber",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره بیمه"
                    ),
                ),
                (
                    "IsActive",
                    models.BooleanField(default=True, verbose_name="کاربر فعال است؟"),
                ),
                (
                    "BirthCity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.city",
                        verbose_name="شهر محل تولد",
                    ),
                ),
                (
                    "ContractType",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ContractType",
                        to="HR.constvalue",
                        verbose_name="نوع قرارداد",
                    ),
                ),
                (
                    "DegreeType",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="HR.constvalue",
                        verbose_name="آخرین مقطع تحصیلی",
                    ),
                ),
                (
                    "IdentityCity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="IdentityCity",
                        to="HR.city",
                        verbose_name="شهر محل صدور شناسنامه",
                    ),
                ),
                (
                    "LivingAddress",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HR.postaladdress",
                        verbose_name="آدرس محل سکونت",
                    ),
                ),
                (
                    "MarriageStatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="UsersMarriageStatus",
                        to="HR.constvalue",
                        verbose_name="وضعیت تاهل",
                    ),
                ),
                (
                    "MilitaryStatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="UsersMilitaryStatus",
                        to="HR.constvalue",
                        verbose_name="وضعیت خدمت",
                    ),
                ),
                (
                    "Religion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="UsersReligion",
                        to="HR.constvalue",
                        verbose_name="دین",
                    ),
                ),
                (
                    "UserStatus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserStatus",
                        to="HR.constvalue",
                        verbose_name="وضعیت کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "db_table": "Users",
            },
        ),
        migrations.CreateModel(
            name="UserTeamRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Superior", models.BooleanField(default=False, verbose_name="ارشد")),
                (
                    "StartDate",
                    models.CharField(max_length=10, verbose_name="تاریخ شروع"),
                ),
                (
                    "EndDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "LevelId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.rolelevel",
                        verbose_name="سطح",
                    ),
                ),
                (
                    "ManagerUserName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserTeamRoleManagerUserNames",
                        to="HR.users",
                        verbose_name="نام مدیر",
                    ),
                ),
                (
                    "RoleId",
                    models.ForeignKey(
                        db_column="RoleId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.role",
                        verbose_name="کد سمت",
                    ),
                ),
                (
                    "TeamCode",
                    models.ForeignKey(
                        db_column="TeamCode",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.team",
                        verbose_name="کدتیم",
                    ),
                ),
                (
                    "UserName",
                    models.ForeignKey(
                        db_column="UserName",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserTeamRoleUserNames",
                        to="HR.users",
                        verbose_name="نام کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات پرسنل",
                "verbose_name_plural": "اطلاعات همه ی پرسنل",
                "db_table": "UserTeamRole",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150, verbose_name="نام دانشگاه")),
                (
                    "UniversityType",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "دولتی"),
                            (2, "دانشگاه آزاد اسلامی"),
                            (3, "غیرانتفاعی"),
                            (4, "علمی و کاربردی"),
                            (5, "پیام نور"),
                            (6, "مجازی"),
                        ],
                        help_text="دیگر از این فیلد برای تعیین نوع دانشگاه استفاده نمی کنیم",
                        null=True,
                        verbose_name="نوع دانشگاه",
                    ),
                ),
                (
                    "UniversityCity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.city",
                        verbose_name="شهر محل دانشگاه",
                    ),
                ),
                (
                    "University_Type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"IsActive": True},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="HR.constvalue",
                        verbose_name="نوع دانشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دانشگاه",
                "verbose_name_plural": "دانشگاه ها",
            },
        ),
        migrations.CreateModel(
            name="Tendency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=150, verbose_name="گرایش")),
                (
                    "FieldOfStudy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.fieldofstudy",
                        verbose_name="گرایش تحصیلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "گرایش تحصیلی",
                "verbose_name_plural": "گرایش های تحصیلی",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="GeneralManager",
            field=models.ForeignKey(
                help_text="مدیر عمومی می تواند، مدیر پروژه یا مدیر اداری، یا  مدیر اداری یا کلا هر مدیری باشد",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="TeamGeneralManager",
                to="HR.users",
                verbose_name="مدیر عمومی",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="SupportManager",
            field=models.ForeignKey(
                help_text="برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="TeamSupportManager",
                to="HR.users",
                verbose_name="مدیر پشتیبانی",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="TestManager",
            field=models.ForeignKey(
                help_text="برای تیم های عملیانی مشخص می شود و برای غیر عملیاتی ها نال است",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="TeamTestManager",
                to="HR.users",
                verbose_name="مدیر تست",
            ),
        ),
        migrations.CreateModel(
            name="RoleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RoleGroup", models.CharField(max_length=50, verbose_name="گروه")),
                (
                    "RoleGroupName",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name=" نام گروه"
                    ),
                ),
                (
                    "RoleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="RoleGroupRoleIDs",
                        to="HR.role",
                        verbose_name="سمت فعلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "گروه سمت",
                "verbose_name_plural": "گروه های سمت ها",
            },
        ),
        migrations.CreateModel(
            name="PreviousUserTeamRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Superior", models.BooleanField(default=False, verbose_name="ارشد")),
                (
                    "StartDate",
                    models.CharField(max_length=10, verbose_name="تاریخ شروع"),
                ),
                (
                    "EndDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "LevelId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.rolelevel",
                        verbose_name="سطح",
                    ),
                ),
                (
                    "ManagerUserName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ManagerUserNames",
                        to="HR.users",
                        verbose_name="نام مدیر",
                    ),
                ),
                (
                    "RoleId",
                    models.ForeignKey(
                        db_column="RoleId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.role",
                        verbose_name="کد سمت",
                    ),
                ),
                (
                    "TeamCode",
                    models.ForeignKey(
                        db_column="TeamCode",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.team",
                        verbose_name="کدتیم",
                    ),
                ),
                (
                    "UserName",
                    models.ForeignKey(
                        db_column="UserName",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserNames",
                        to="HR.users",
                        verbose_name="نام کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات پرسنل",
                "verbose_name_plural": "اطلاعات همه ی پرسنل",
                "db_table": "PreviousUserTeamRole",
            },
        ),
        migrations.AddField(
            model_name="postaladdress",
            name="Person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="HR.users",
                verbose_name="فرد",
            ),
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TelNumber",
                    models.BigIntegerField(
                        help_text=" شماره ثابت بدون داخلی وارد شود. (مثلا : 87654321) شماره موبایل بدون صفر وارد شود مثلاً 9121234567",
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "IsDefault",
                    models.BooleanField(default=False, verbose_name="پیش فرض"),
                ),
                (
                    "Person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_number",
                        to="HR.users",
                        verbose_name="فرد",
                    ),
                ),
                (
                    "Province",
                    models.ForeignKey(
                        blank=True,
                        help_text="این فیلد زمانی پر می شود که تلفن خط ثابت باشد",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HR.province",
                        verbose_name="استان",
                    ),
                ),
                (
                    "TelType",
                    models.ForeignKey(
                        help_text="منظور از نوع این است که می تواند، محل زندگی، همراه، ضروری و... باشد",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="HR.constvalue",
                        verbose_name="نوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "شماره تماس",
                "verbose_name_plural": "شماره های تماس",
            },
        ),
        migrations.CreateModel(
            name="PagePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GroupId", models.PositiveIntegerField(verbose_name="شناسه گروه")),
                (
                    "Editable",
                    models.BooleanField(default=False, verbose_name="قابل ویرایش"),
                ),
                (
                    "Page",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.pageinformation",
                        verbose_name="نام صفحه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی صفحه",
                "verbose_name_plural": "دسترسی های صفحات",
            },
        ),
        migrations.CreateModel(
            name="OrganizationChartTeamRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RoleCount",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ظرفیت سمت"
                    ),
                ),
                (
                    "ManagerUserName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OrganizationChartTeamRoleManagerUserNames",
                        to="HR.users",
                        verbose_name="نام مدیر",
                    ),
                ),
                (
                    "OrganizationChartRole",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.organizationchartrole",
                        verbose_name="مدیر تیم و سمت",
                    ),
                ),
                (
                    "TeamCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="OrganizationChartTeamRoleTeamCodes",
                        to="HR.team",
                        verbose_name="نام تیم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سمت  تیم",
                "verbose_name_plural": "سمت های تیم های عملیاتی",
            },
        ),
        migrations.AddField(
            model_name="organizationchartrole",
            name="LevelId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrganizationChartRoleRoleLevels",
                to="HR.rolelevel",
                verbose_name="سطح ",
            ),
        ),
        migrations.AddField(
            model_name="organizationchartrole",
            name="RoleId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OrganizationChartRoleRoleIDs",
                to="HR.role",
                verbose_name="سمت",
            ),
        ),
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254, verbose_name="ادرس ایمیل")),
                (
                    "Title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "IsDefault",
                    models.BooleanField(
                        default=False, verbose_name="آدرس ایمیل پیشفرض است؟"
                    ),
                ),
                (
                    "Person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HR.users",
                        verbose_name="فرد",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس پست الکترونیکی",
                "verbose_name_plural": "آدرس های پست الکترونیکی",
            },
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "DegreeType",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "زیر دیپلم"),
                            (2, "دیپلم"),
                            (3, "کاردانی"),
                            (4, "کارشناسی"),
                            (5, "فوق کارشناسی"),
                            (6, "دکترا"),
                        ],
                        help_text="دیگر از این فیلد برای نوع مقطع مدرک تحصیلی استفاده نمی کنیم.",
                        null=True,
                        verbose_name="مقطع تحصیلی",
                    ),
                ),
                (
                    "StartDate",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "EndDate",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ خاتمه"),
                ),
                (
                    "StartYear",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="تاریخ شمسی",
                        null=True,
                        verbose_name="سال ورود",
                    ),
                ),
                (
                    "EndYear",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="تاریخ شمسی",
                        null=True,
                        verbose_name="سال فراغت از تحصیل",
                    ),
                ),
                (
                    "IsStudent",
                    models.BooleanField(default=False, verbose_name="دانشجو است؟"),
                ),
                (
                    "GPA",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="معدل",
                    ),
                ),
                (
                    "Degree_Type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="HR.constvalue",
                        verbose_name=" مقطع تحصیلی",
                    ),
                ),
                (
                    "EducationTendency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="HR.tendency",
                        verbose_name="گرایش تحصیلی",
                    ),
                ),
                (
                    "Person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_history",
                        to="HR.users",
                        verbose_name="پرسنل",
                    ),
                ),
                (
                    "University",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="HR.university",
                        verbose_name="دانشگاه محل تحصیل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سابقه تحصیلی",
                "verbose_name_plural": "سوابق تحصیلی",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="Province",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="HR.province",
                verbose_name="استان مربوطه",
            ),
        ),
        migrations.CreateModel(
            name="ChangeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Superior",
                    models.BooleanField(default=False, verbose_name="وضعیت فعلی ارشد"),
                ),
                (
                    "SuperiorTarget",
                    models.BooleanField(default=False, verbose_name="وضعیت جدید ارشد"),
                ),
                (
                    "Education",
                    models.BooleanField(default=True, verbose_name="آموزش نیاز دارد؟"),
                ),
                (
                    "Educator",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="آموزش دهنده",
                    ),
                ),
                (
                    "Evaluation",
                    models.BooleanField(
                        default=True, verbose_name="ارزیابی نیاز دارد؟"
                    ),
                ),
                (
                    "Assessor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ارزیابی کننده",
                    ),
                ),
                (
                    "RequestGap",
                    models.IntegerField(blank=True, null=True, verbose_name="مدت زمان"),
                ),
                (
                    "Assessor2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ارزیابی کننده دوم",
                    ),
                ),
                (
                    "ReEvaluation",
                    models.BooleanField(
                        default=True, verbose_name="ارزیابی  دوم نیاز دارد؟"
                    ),
                ),
                (
                    "PmChange",
                    models.BooleanField(default=True, verbose_name="تغیرات PM؟"),
                ),
                (
                    "ITChange",
                    models.BooleanField(default=True, verbose_name="تغیرات IT؟"),
                ),
                (
                    "LevelId",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ChangeRoleRoleLevels",
                        to="HR.rolelevel",
                        verbose_name="سطح فعلی",
                    ),
                ),
                (
                    "LevelIdTarget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ChangeRoleLevelIdTargets",
                        to="HR.rolelevel",
                        verbose_name="سطح جدید",
                    ),
                ),
                (
                    "RoleID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ChangeRoleRoleIDs",
                        to="HR.role",
                        verbose_name="سمت فعلی",
                    ),
                ),
                (
                    "RoleIdTarget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ChangeRoleRoleIdTargets",
                        to="HR.role",
                        verbose_name="سمت جدید",
                    ),
                ),
            ],
            options={
                "verbose_name": "اطلاعات تغییر سمت",
                "verbose_name_plural": "اطلاعات تغییر سمت ها",
            },
        ),
        migrations.CreateModel(
            name="AccessPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "UserName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AccessPersonnelUserNames",
                        to="HR.users",
                        verbose_name="نام کاربری",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسترسی انتخاب  سمت",
                "verbose_name_plural": "دسترسی های انتخاب همه سمت ها",
            },
        ),
    ]
