# Generated by Django 4.2 on 2023-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="IsActive",
            field=models.BooleanField(
                default=True, null=True, verbose_name="آیا تیم فعال است؟"
            ),
        ),
    ]
