# Generated by Django 4.2 on 2023-12-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0002_alter_team_isactive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="BirthCity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="HR.city",
                verbose_name="شهر محل تولد",
            ),
        ),
    ]
