# Generated by Django 4.2 on 2023-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0003_alter_users_birthcity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userteamrole",
            name="StartDate",
            field=models.CharField(max_length=10, null=True, verbose_name="تاریخ شروع"),
        ),
        migrations.AlterField(
            model_name="userteamrole",
            name="Superior",
            field=models.BooleanField(default=False, null=True, verbose_name="ارشد"),
        ),
    ]
