# Generated by Django 4.2 on 2024-01-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_alter_userteamrole_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='LastBuilding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersBuilding', to='HR.constvalue'),
        ),
        migrations.AddField(
            model_name='users',
            name='LastFloor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UsersFloor', to='HR.constvalue'),
        ),
    ]
