# Generated by Django 4.2 on 2023-12-21 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsOrdersPerDay',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Item', models.PositiveIntegerField(verbose_name='آیتم')),
                ('Date', models.CharField(max_length=10, verbose_name='سفارش برای')),
                ('TotalOrders', models.PositiveIntegerField(verbose_name='مجموع سفارش ها')),
            ],
            options={
                'verbose_name': 'تعداد سفارش بر حسب آیتم',
                'verbose_name_plural': 'تعداد سفارشات بر حسب آیتم',
                'db_table': 'ItemsOrdersPerDay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Personnel', models.CharField(max_length=250, verbose_name='پرسنل')),
                ('FirstName', models.CharField(max_length=250, verbose_name='نام')),
                ('LastName', models.CharField(max_length=250, verbose_name='نام خانوادگی')),
                ('DeliveryDate', models.CharField(max_length=10, verbose_name='سفارش برای')),
                ('SubsidyCap', models.PositiveIntegerField(verbose_name='یارانه فناوران به تومان')),
                ('TotalPrice', models.PositiveIntegerField(verbose_name='مبلغ کل سفارش به تومان')),
                ('PersonnelDebt', models.PositiveIntegerField(verbose_name='بدهی به تومان')),
                ('SubsidySpent', models.PositiveIntegerField(verbose_name='خرج فناوران')),
                ('openForBreakfast', models.BooleanField()),
                ('openForLaunch', models.BooleanField()),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'db_table': 'Order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnelDailyReport',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Personnel', models.CharField(max_length=250)),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('TeamName', models.CharField(max_length=250)),
                ('RoleName', models.CharField(max_length=250)),
                ('ItemName', models.CharField(max_length=500, verbose_name='نام ایتم')),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('DeliveryDate', models.CharField(max_length=10, verbose_name='سفارش برای')),
            ],
            options={
                'db_table': 'PersonnelDailyReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=300, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ایتم',
                'verbose_name_plural': 'دسته بندی ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableDate', models.CharField(max_length=10, verbose_name='قابل سفارش برای')),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منو ها',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HolidayDate', models.CharField(max_length=10, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'تعطیل رسمی',
                'verbose_name_plural': 'تعطیلات رسمی',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500, verbose_name='نام ایتم')),
                ('MealType', models.CharField(choices=[('BRF', 'صبحانه'), ('LNC', 'ناهار')], default='BRF', max_length=3)),
                ('ItemDesc', models.TextField(blank=True, null=True, verbose_name='شرح ایتم')),
                ('IsActive', models.BooleanField(default=True)),
                ('Image', models.ImageField(blank=True, help_text='در صورتی که عکس آپلود نشود سیستم به صورت خودکار عکس پیشفرض قرار می دهد', null=True, upload_to='media/items/')),
                ('CurrentPrice', models.PositiveIntegerField(help_text='برای تغییر این فیلد باید رکورد جدید در تاریخچه قیمت مربوط به این آیتم ایجاد کنید', verbose_name='قیمت فعلی آیتم به تومان')),
            ],
            options={
                'verbose_name': 'اطلاعات ایتم',
                'verbose_name_plural': 'اطلاعات ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='ItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.PositiveIntegerField(verbose_name='قیمت به تومان')),
                ('FromDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('UntilDate', models.CharField(help_text='توجه شود که تاریخ شروع و پایان یک رکورد نیز با همان قیمت حساب می شود', max_length=10, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت آیتم',
                'verbose_name_plural': 'تاریخچه قیمت آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel', models.CharField(max_length=250, verbose_name='پرسنل')),
                ('DeliveryDate', models.CharField(max_length=10, verbose_name='سفارش برای')),
                ('Quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('PricePerOne', models.PositiveIntegerField(verbose_name='قیمت به تومان')),
            ],
            options={
                'verbose_name': 'آیتم سفارشی',
                'verbose_name_plural': 'آیتم های سفارشی',
            },
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField(verbose_name='سهم فناوران به تومان')),
                ('FromDate', models.CharField(max_length=10, verbose_name='تاریخ شروع')),
                ('UntilDate', models.CharField(help_text='خود تاریخ شروع و پایان نیز با همین سوبسید محاسبه می شود', max_length=10, null=True, verbose_name='تاریخ پایان')),
            ],
            options={
                'verbose_name': 'یارانه',
                'verbose_name_plural': 'یارانه ها',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsSystemOpenForPersonnel', models.BooleanField(default=True, help_text='در صورت بسته بودن برای پرسنل استاتوس در دسترس نبودن سیستم به کاربر نمایش داده می شود و ریکوعست های سمت بک پردازش نمی شوند')),
                ('IsSystemOpenForAdmin', models.BooleanField(default=True, help_text='مانند فیلد بالا')),
                ('SystemUpdating', models.BooleanField(default=False, help_text='هنگام آپدیت کردن سیستم گزینه را فعال کرده تا به یوزر نشان دهد که سیستم در حال آپدیت شدن است و امکان ثبت سفارش فعال نیست')),
                ('SuperAdmins', models.CharField(max_length=250, null=True)),
                ('BreakfastRegistrationWindowHours', models.IntegerField(default=0)),
                ('BreakfastRegistrationWindowDays', models.IntegerField(default=0)),
                ('LaunchRegistrationWindowHours', models.IntegerField(default=0)),
                ('LaunchRegistrationWindowDays', models.IntegerField(default=0)),
                ('IsSystemOpenForLaunchSubmission', models.BooleanField(default=False, help_text='سیستم خدمات مربوط به ناهار را انجام می دهد یا خیر')),
                ('IsSystemOpenForBreakfastSubmission', models.BooleanField(default=True, help_text='سیستم خدمات مربوط به صبحانه را انجام می دهد یا خیر')),
                ('TotalItemsCanOrderedForBreakfastByPersonnel', models.PositiveSmallIntegerField(default=1, help_text='در حال حاضر با توجه به قوانین واحد اداری هر فرد از منوی صبحانه فقط یک ایتم می تونه سفارش بده.این فیلد جمع ایتم های قابل سفارش برای صبحانه را تعیین می کند', null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='subsidy',
            constraint=models.UniqueConstraint(fields=('UntilDate',), name='untildate_unique'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='آیتم'),
        ),
        migrations.AddField(
            model_name='itempricehistory',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='ایتم'),
        ),
        migrations.AddField(
            model_name='item',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='dailymenuitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='ایتم'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('Personnel', 'DeliveryDate', 'Item'), name='unique_item_date_personnel'),
        ),
        migrations.AddConstraint(
            model_name='dailymenuitem',
            constraint=models.UniqueConstraint(fields=('AvailableDate', 'Item'), name='unique_AvailableDate_Item'),
        ),
    ]
