# Generated by Django 4.2 on 2023-11-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=300, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ایتم',
                'verbose_name_plural': 'دسته بندی ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HolidayDate', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500, verbose_name='نام ایتم')),
                ('ItemDesc', models.TextField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Image', models.CharField(blank=True, max_length=500, null=True)),
                ('CurrentPrice', models.PositiveIntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'اطلاعات ایتم',
                'verbose_name_plural': 'اطلاعات ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel', models.CharField(max_length=250)),
                ('DeliveryDate', models.CharField(max_length=10)),
                ('IsDeleted', models.BooleanField(default=True, help_text='IsDeleted?(Soft Delete)')),
                ('AppliedSubsidy', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField()),
                ('FromDate', models.CharField(max_length=10)),
                ('UntilDate', models.CharField(help_text='برای تاکید کردن روی غیر قابل استفاده بودن سوبسید این فیلد باید False شود در واقع این محدودیت دیتابیسی است که منطق unique بودن سوبسید فعال را تضمین می کند', max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveSmallIntegerField(default=1)),
                ('PricePerOne', models.PositiveIntegerField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.order')),
                ('OrderedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.PositiveIntegerField()),
                ('FromDate', models.CharField(max_length=10)),
                ('UntilDate', models.CharField(max_length=10, null=True, unique=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableDate', models.CharField(max_length=10)),
                ('IsActive', models.BooleanField(default=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
            ],
        ),
    ]
