# Generated by Django 4.2 on 2023-11-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActionAt', models.DateTimeField(auto_now_add=True)),
                ('User', models.CharField(max_length=250)),
                ('ActionCode', models.CharField(choices=[('ORDER_CREATION', 'سفارش جدید'), ('ORDER_MODIFICATION', 'تغییر سفارش')], max_length=250)),
                ('ActionDesc', models.TextField()),
                ('AdminActionReason', models.TextField(null=True)),
                ('SearchableKey', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=300, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ایتم',
                'verbose_name_plural': 'دسته بندی ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableDate', models.DateField()),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('IsOfficial', models.BooleanField(default=False)),
                ('Reason', models.TextField(blank=True, help_text='برای تعطیلات غیر رسمی ذکر شود.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500, verbose_name='نام ایتم')),
                ('ItemDesc', models.TextField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to='media/items/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'اطلاعات ایتم',
                'verbose_name_plural': 'اطلاعات ایتم ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel', models.CharField(max_length=250)),
                ('DeliveryDate', models.DateField()),
                ('IsActive', models.BooleanField(default=True, help_text='IsDeleted?(Soft Delete)')),
            ],
        ),
        migrations.CreateModel(
            name='Subsidy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('IsActive', models.BooleanField(default=False, help_text='برای تاکید کردن روی غیر قابل استفاده بودن سوبسید این فیلد باید False شود در واقع این محدودیت دیتابیسی است که منطق unique بودن سوبسید فعال را تضمین می کند', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveSmallIntegerField(default=1)),
                ('OrderedFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.dailymenuitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.PositiveIntegerField()),
                ('IsActive', models.BooleanField()),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
            ],
        ),
        migrations.AddField(
            model_name='dailymenuitem',
            name='PriceItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.itemprice'),
        ),
    ]
