# Generated by Django 4.2 on 2023-11-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymenuitem',
            options={'verbose_name': 'منو', 'verbose_name_plural': 'منو ها'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'تعطیل رسمی', 'verbose_name_plural': 'تعطیلات رسمی'},
        ),
        migrations.AlterModelOptions(
            name='itempricehistory',
            options={'verbose_name': 'تاریخچه قیمت آیتم', 'verbose_name_plural': 'تاریخچه قیمت آیتم ها'},
        ),
        migrations.AlterModelOptions(
            name='itemsordersperday',
            options={'managed': False, 'verbose_name': 'تعداد سفارش بر حسب آیتم', 'verbose_name_plural': 'تعداد سفارشات بر حسب آیتم'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارشی', 'verbose_name_plural': 'آیتم های سفارشی'},
        ),
        migrations.AlterModelOptions(
            name='subsidy',
            options={'verbose_name': 'یارانه', 'verbose_name_plural': 'یارانه ها'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='OrderedItem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='آیتم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='AvailableDate',
            field=models.CharField(max_length=10, verbose_name='قابل سفارش برای'),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='ایتم'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='HolidayDate',
            field=models.CharField(max_length=10, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='CurrentPrice',
            field=models.PositiveIntegerField(help_text='برای تغییر این فیلد باید رکورد جدید در تاریخچه قیمت مربوط به این آیتم ایجاد کنید', verbose_name='قیمت فعلی آیتم به تومان'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, help_text='در صورتی که عکس آپلود نشود سیستم به صورت خودکار عکس پیشفرض قرار می دهد', null=True, upload_to='media/items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemDesc',
            field=models.TextField(blank=True, null=True, verbose_name='شرح ایتم'),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='FromDate',
            field=models.CharField(max_length=10, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item', verbose_name='ایتم'),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='Price',
            field=models.PositiveIntegerField(verbose_name='قیمت به تومان'),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='UntilDate',
            field=models.CharField(help_text='توجه شود که تاریخ شروع و پایان یک رکورد نیز با همان قیمت حساب می شود', max_length=10, null=True, unique=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='DeliveryDate',
            field=models.CharField(max_length=10, verbose_name='سفارش برای'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Personnel',
            field=models.CharField(max_length=250, verbose_name='پرسنل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='PricePerOne',
            field=models.PositiveIntegerField(verbose_name='قیمت به تومان'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='Amount',
            field=models.PositiveIntegerField(verbose_name='سهم فناوران به تومان'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='FromDate',
            field=models.CharField(max_length=10, verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='UntilDate',
            field=models.CharField(help_text='خود تاریخ شروع و پایان نیز با همین سوبسید محاسبه می شود', max_length=10, null=True, verbose_name='تاریخ پایان'),
        ),
    ]
