# Generated by Django 4.2 on 2023-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/items/'),
        ),
    ]
