# Generated by Django 4.2 on 2023-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailymenuitem',
            constraint=models.UniqueConstraint(fields=('AvailableDate', 'Item'), name='unique_AvailableDate_Item'),
        ),
    ]
