# Generated by Django 4.2 on 2023-12-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personnel', models.CharField(max_length=250)),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('IsAdmin', models.BooleanField(default=False)),
                ('Key', models.CharField(max_length=64)),
                ('ExpiredAt', models.CharField(max_length=10)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('Personnel',), name='unique_personnel'),
        ),
    ]
