# Generated by Django 4.2 on 2023-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pors", "0002_dailymenuitem_unique_availabledate_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"managed": False},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="Order",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="DeliveryDate",
            field=models.CharField(default="1402/02/06", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="Personnel",
            field=models.CharField(default="e.rezaee@eit", max_length=250),
            preserve_default=False,
        ),
    ]
