# Generated by Django 4.2 on 2023-12-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pors", "0002_alter_dailymenuitem_options_alter_holiday_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "IsSystemOpenForPersonnel",
                    models.BooleanField(
                        default=True,
                        help_text="در صورت بسته بودن برای پرسنل استاتوس در دسترس نبودن سیستم به کاربر نمایش داده می شود و ریکوعست های سمت بک پردازش نمی شوند",
                    ),
                ),
                (
                    "IsSystemOpenForAdmin",
                    models.BooleanField(default=True, help_text="مانند فیلد بالا"),
                ),
                (
                    "SystemUpdating",
                    models.BooleanField(
                        default=False,
                        help_text="هنگام آپدیت کردن سیستم گزینه را فعال کرده تا به یوزر نشان دهد که سیستم در حال آپدیت شدن است و امکان ثبت سفارش فعال نیست",
                    ),
                ),
                ("SuperAdmins", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="MealType",
            field=models.CharField(
                choices=[("BRF", "صبحانه"), ("LNC", "ناهار")],
                default="BRF",
                max_length=3,
            ),
        ),
    ]
