# Generated by Django 4.2 on 2023-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0002_user_user_unique_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
