# Generated by Django 4.2 on 2023-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
