# Generated by Django 4.2 on 2023-12-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0003_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Key',
            new_name='Token',
        ),
    ]
