# Generated by Django 4.2 on 2023-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pors", "0003_systemsetting_item_mealtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="BreakfastRegistrationWindowHours",
            field=models.PositiveIntegerField(
                default=0,
                help_text="فرض کنیم 48 باشه این عدد. یعنی اینکه برای ثبت سفارش صبحانه امروز کاربر  باید 48 ساعت پیش صبحانه اش را ثبت سفارش کرده باشد یا به عبارت دیگر از الان برای پس از 48 ساعت اینده می تواند ثبت سفارش صبحانه کند",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="IsSystemOpenForBreakfastSubmission",
            field=models.BooleanField(
                default=True,
                help_text="سیستم خدمات مربوط به صبحانه را انجام می دهد یا خیر",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="IsSystemOpenForLaunchSubmission",
            field=models.BooleanField(
                default=False,
                help_text="سیستم خدمات مربوط به ناهار را انجام می دهد یا خیر",
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="LaunchRegistrationWindowHours",
            field=models.PositiveIntegerField(
                default=0, help_text="مانند فیلد BreakfastRegistrationWindowHours"
            ),
        ),
    ]
