# Generated by Django 4.2 on 2023-12-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0004_rename_key_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LastName',
        ),
    ]
