# Generated by Django 4.2 on 2023-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pors", "0004_systemsetting_breakfastregistrationwindowhours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="TotalItemsCanOrderedForBreakfastByPersonnel",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="در حال حاضر با توجه به قوانین واحد اداری هر فرد از منوی صبحانه فقط یک ایتم می تونه سفارش بده.این فیلد جمع ایتم های قابل سفارش برای صبحانه را تعیین می کند",
                null=True,
            ),
        ),
    ]
