# Generated by Django 4.2 on 2023-12-25 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0005_rename_firstname_user_fullname_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='CreatedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ModifiedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
