# Generated by Django 4.2 on 2023-12-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0005_systemsetting_totalitemscanorderedforbreakfastbypersonnel'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('Personnel', 'DeliveryDate', 'Item'), name='unique_item_date_personnel'),
        ),
    ]
