# Generated by Django 4.2 on 2023-12-26 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0006_orderitem_createdat_orderitem_modifiedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='ActionAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ActionDesc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ActionType',
            field=models.CharField(choices=[('C', 'create'), ('R', 'read'), ('U', 'update'), ('D', 'delete')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actionlog',
            name='OldData',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ReferencedRecordId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='TabelName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='User',
            field=models.CharField(default='jj', max_length=250),
            preserve_default=False,
        ),
    ]
