# Generated by Django 4.2 on 2023-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pors", "0006_orderitem_unique_item_date_personnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="DeliveryPlace",
            field=models.CharField(
                choices=[("PAD", "ساختمان پدیدار"), ("OTH", "ساختمان دیگر")],
                default="PAD",
                help_text="محل تحویل سفارش فرقی نمی کند که صبحانه باشد یا ناهار. هر چیزی که سفارش دهید یک جا تحویل می گیرید",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
