# Generated by Django 4.2 on 2023-12-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0007_orderitem_deliveryplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='DeliveryPlace',
        ),
    ]
