# Generated by Django 4.2 on 2023-12-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0007_actionlog_actionat_actionlog_actiondesc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='TabelName',
            new_name='TableName',
        ),
    ]
