# Generated by Django 4.2 on 2024-01-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0008_rename_tabelname_actionlog_tablename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-ActionAt']},
        ),
    ]
