# Generated by Django 4.2 on 2023-12-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0008_remove_orderitem_deliveryplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelDailyReport',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Personnel', models.CharField(max_length=250)),
                ('FirstName', models.CharField(max_length=250)),
                ('LastName', models.CharField(max_length=250)),
                ('TeamName', models.CharField(max_length=250)),
                ('RoleName', models.CharField(max_length=250)),
                ('ItemName', models.CharField(max_length=500, verbose_name='نام ایتم')),
                ('Quantity', models.PositiveSmallIntegerField()),
                ('DeliveryDate', models.CharField(max_length=10, verbose_name='سفارش برای')),
            ],
            options={
                'db_table': 'PersonnelDailyReport',
                'managed': False,
            },
        ),
    ]
