# Generated by Django 4.2 on 2023-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0009_personneldailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='BreakfastRegistrationWindowDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='LaunchRegistrationWindowDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='UntilDate',
            field=models.CharField(help_text='خود تاریخ شروع و پایان نیز با همین سوبسید محاسبه می شود', max_length=10, null=True, unique=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='BreakfastRegistrationWindowHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='LaunchRegistrationWindowHours',
            field=models.IntegerField(default=0),
        ),
    ]
