# Generated by Django 4.2 on 2024-01-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0009_alter_actionlog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Today', models.PositiveSmallIntegerField()),
                ('MealType', models.CharField(choices=[('BRF', 'صبحانه'), ('LNC', 'ناهار')], max_length=3)),
                ('Days', models.PositiveSmallIntegerField(default=0)),
                ('Hour', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailymenuitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itempricehistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemsordersperday',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subsidy',
            options={},
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='BreakfastRegistrationWindowDays',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='BreakfastRegistrationWindowHours',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='LaunchRegistrationWindowDays',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='LaunchRegistrationWindowHours',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='SuperAdmins',
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='AvailableDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dailymenuitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='HolidayDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='CurrentPrice',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='FromDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item'),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='Price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itempricehistory',
            name='UntilDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='DeliveryDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Personnel',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='PricePerOne',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='Amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='FromDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='UntilDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='IsSystemOpenForAdmin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='IsSystemOpenForBreakfastSubmission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='IsSystemOpenForLaunchSubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='IsSystemOpenForPersonnel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='SystemUpdating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='TotalItemsCanOrderedForBreakfastByPersonnel',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
