# Generated by Django 4.2 on 2023-12-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0010_systemsetting_breakfastregistrationwindowdays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempricehistory',
            name='UntilDate',
            field=models.CharField(help_text='توجه شود که تاریخ شروع و پایان یک رکورد نیز با همان قیمت حساب می شود', max_length=10, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='UntilDate',
            field=models.CharField(help_text='خود تاریخ شروع و پایان نیز با همین سوبسید محاسبه می شود', max_length=10, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AddConstraint(
            model_name='subsidy',
            constraint=models.UniqueConstraint(fields=('UntilDate',), name='untildate_unique'),
        ),
    ]
