# Generated by Django 4.2 on 2024-01-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0010_deadlines_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deadlines',
            old_name='Today',
            new_name='WeekDay',
        ),
    ]
