# Generated by Django 4.2 on 2024-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0011_rename_today_deadlines_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='DeliveryBuilding',
            field=models.CharField(default='b1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='DeliveryFloor',
            field=models.CharField(default='b1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='LastDeliveryBuilding',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LastDeliveryFloor',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
