# Generated by Django 4.2 on 2024-02-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0012_orderitem_deliverybuilding_orderitem_deliveryfloor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='Admin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ManipulationReason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
