# Generated by Django 4.0.1 on 2024-07-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0013_actionlog_admin_actionlog_manipulationreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_constvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=100)),
                ('IsActive', models.BooleanField(default=True)),
                ('OrderNumber', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('ConstValue', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'HR_constvalue',
            },
        ),
        migrations.CreateModel(
            name='TempUsers',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('NationalCode', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
