# Generated by Django 4.2 on 2024-07-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0014_hr_constvalue_tempusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProviderOrdering',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=250)),
                ('MealType', models.CharField(max_length=250)),
                ('PricePerOne', models.PositiveIntegerField()),
                ('ItemTotalCount', models.PositiveIntegerField()),
                ('DeliveryDate', models.CharField(max_length=10)),
                ('DeliveryBuilding', models.CharField(max_length=10)),
                ('FoodProvider', models.PositiveIntegerField()),
                ('FoodProviderPersian', models.CharField(max_length=10)),
                ('DeliveryBuildingPersian', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'FoodProviderOrdering',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminManipulationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ManipulationReasonComment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemProvider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pors.itemprovider'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='ManipulationReason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pors.adminmanipulationreason'),
        ),
    ]
