# Generated by Django 4.2 on 2024-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0014_hr_constvalue_tempusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
