# Generated by Django 4.2 on 2024-07-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0014_hr_constvalue_tempusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminManipulationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='actionlog',
            name='ManipulationReasonComment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='ManipulationReason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pors.adminmanipulationreason'),
        ),
    ]
