# Generated by Django 4.2 on 2024-07-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0015_foodproviderordering_adminmanipulationreason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr_constvalue',
            options={'ordering': ['Parent_id', 'OrderNumber'], 'verbose_name': 'مقدار ثابت', 'verbose_name_plural': 'مقادیر ثابت'},
        ),
        migrations.AddField(
            model_name='hr_constvalue',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pors.hr_constvalue', verbose_name='شناسه پدر'),
        ),
    ]
