# Generated by Django 4.2 on 2024-07-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0015_itemprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ItemProvider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pors.itemprovider'),
            preserve_default=False,
        ),
    ]
