# Generated by Django 4.2 on 2024-07-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0016_item_itemprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProviderOrdering',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=250)),
                ('MealType', models.CharField(max_length=250)),
                ('PricePerOne', models.PositiveIntegerField()),
                ('ItemTotalCount', models.PositiveIntegerField()),
                ('DeliveryDate', models.CharField(max_length=10)),
                ('DeliveryBuilding', models.CharField(max_length=10)),
                ('FoodProvider', models.PositiveIntegerField()),
                ('FoodProviderPersian', models.CharField(max_length=10)),
                ('DeliveryBuildingPersian', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'FoodProviderOrdering',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='itemprovider',
            old_name='title',
            new_name='Title',
        ),
    ]
