# Generated by Django 4.2 on 2024-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0016_alter_hr_constvalue_options_hr_constvalue_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmanipulationreason',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='adminmanipulationreason',
            name='ReasonCode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
