# Generated by Django 4.2 on 2024-07-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0015_adminmanipulationreason_and_more'),
        ('pors', '0017_foodproviderordering_rename_title_itemprovider_title'),
    ]

    operations = [
    ]
