# Generated by Django 4.2 on 2024-07-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0017_rename_title_adminmanipulationreason_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='IsPrimary',
            field=models.BooleanField(default=False),
        ),
    ]
