# Generated by Django 4.2 on 2024-07-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0018_category_isprimary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='TotalItemsCanOrderedForBreakfastByPersonnel',
        ),
    ]
