# Generated by Django 4.2 on 2024-07-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0019_remove_systemsetting_totalitemscanorderedforbreakfastbypersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmanipulationreason',
            name='Title',
            field=models.CharField(max_length=350),
        ),
    ]
