# Generated by Django 4.2 on 2024-07-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0020_alter_adminmanipulationreason_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EmailNotif',
            field=models.BooleanField(default=False),
        ),
    ]
