# Generated by Django 4.2 on 2024-07-13 12:47

from django.db import migrations, models
import django.db.models.deletion
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0020_alter_adminmanipulationreason_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('L', 'دوست داشتم'), ('D', 'دوست نداشتم')], max_length=1)),
                ('Created', models.CharField(default=pors.models.localnow_str, max_length=20)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('Created', models.CharField(default=pors.models.localnow_str, max_length=20)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='Comments',
            field=models.ManyToManyField(related_name='comments', through='pors.ItemComments', to='pors.user'),
        ),
        migrations.AddField(
            model_name='item',
            name='Feedbacks',
            field=models.ManyToManyField(related_name='feedbacks', through='pors.ItemLikes', to='pors.user'),
        ),
    ]
