# Generated by Django 4.2 on 2024-07-13 16:25

from django.db import migrations, models
import django.db.models.deletion
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0021_itemlikes_itemcomments_item_comments_item_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Created', models.CharField(default=pors.models.localnow_str, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ItemLikes',
            new_name='Feedback',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Feedbacks',
        ),
        migrations.DeleteModel(
            name='ItemComments',
        ),
        migrations.AddField(
            model_name='comment',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.user'),
        ),
    ]
