# Generated by Django 4.2 on 2024-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0021_user_emailnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='EmailAddress',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
    ]
