# Generated by Django 4.2 on 2024-07-18 12:14

from django.db import migrations, models
import django.db.models.deletion
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0022_user_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('L', 'دوست داشتم'), ('D', 'دوست نداشتم')], max_length=1)),
                ('Created', models.CharField(default=pors.models.localnow_str, max_length=20)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('Created', models.CharField(default=pors.models.localnow_str, max_length=20)),
                ('Updated', models.CharField(default=pors.models.localnow_str, max_length=20)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
