# Generated by Django 4.2 on 2024-07-16 08:45

from django.db import migrations, models
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0022_comment_rename_itemlikes_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Updated',
            field=models.CharField(default=pors.models.localnow_str, max_length=20),
        ),
    ]
