# Generated by Django 4.2 on 2024-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0022_user_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
