# Generated by Django 4.2 on 2024-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0023_feedback_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFeedbacks',
            fields=[
                ('Id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Item', models.PositiveBigIntegerField()),
                ('TotalLikes', models.PositiveIntegerField()),
                ('TotalDissLikes', models.PositiveIntegerField()),
                ('TotalComments', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ItemFeedbacks',
                'managed': False,
            },
        ),
    ]
