# Generated by Django 4.2 on 2024-07-18 14:41

from django.db import migrations, models
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0024_itemfeedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='ActionAt',
            field=models.CharField(default=pors.models.localnow_str, max_length=20),
        ),
    ]
