# Generated by Django 4.2 on 2024-07-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0025_alter_actionlog_actionat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Pors/ItemImages/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemProvider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pors.itemprovider'),
            preserve_default=False,
        ),
    ]
