# Generated by Django 4.2 on 2024-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0026_orderitem_note_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenuitem',
            name='TotalOrdersAllowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymenuitem',
            name='TotalOrdersLeft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
