# Generated by Django 4.2 on 2024-07-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0027_dailymenuitem_totalordersallowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='EmailNotif',
            field=models.BooleanField(default=True),
        ),
    ]
