# Generated by Django 4.2 on 2024-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0028_alter_user_emailnotif'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='BRFReminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='LNCReminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='RemindBefore',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
