# Generated by Django 4.2 on 2024-07-25 13:45

from django.db import migrations, models
import pors.models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0029_systemsetting_brfreminder_systemsetting_lncreminder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='OldData',
            field=models.JSONField(encoder=pors.models.ActionLog.Encoder, null=True),
        ),
    ]
