# Generated by Django 4.2 on 2024-07-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0030_alter_actionlog_olddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RemindDate', models.CharField(max_length=10)),
                ('MealType', models.CharField(choices=[('BRF', 'صبحانه'), ('LNC', 'ناهار')], max_length=3)),
            ],
        ),
    ]
