# Generated by Django 4.2 on 2024-08-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0031_emailreminderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('PackageDesc', models.TextField(blank=True, null=True)),
                ('FreeItemCount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.item')),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pors.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='Items',
            field=models.ManyToManyField(through='pors.PackageItem', to='pors.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='Packages',
            field=models.ManyToManyField(through='pors.PackageItem', to='pors.package'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pors.package'),
        ),
    ]
