# Generated by Django 4.2 on 2024-08-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0032_package_packageitem_package_items_item_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='PackageDesc',
        ),
        migrations.RemoveField(
            model_name='package',
            name='Title',
        ),
    ]
