# Generated by Django 4.2 on 2024-08-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pors', '0033_remove_package_packagedesc_remove_package_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_item_date_personnel',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('Personnel', 'DeliveryDate', 'Item', 'PackageItem'), name='unique_item_date_personnel'),
        ),
    ]
